import type { Specification } from "../model/specification";
import { normalizeSpecification } from "../normalization/normalize-specification";

/**
 * Loads a published specification page and converts its embedded JSON-LD into
 * the reader's normalized `Specification` model.
 *
 * The expected input is the URL of an HTML documentation page generated by
 * Dataspecer. The page should contain at least one
 * `<script type="application/ld+json">` block.
 */
export async function loadSpecificationFromUrl(url: string): Promise<Specification> {
  const html = await fetchHtmlDocument(url);
  const jsonLdArray = extractJsonLd(html);

  return normalizeSpecification(jsonLdArray, { sourceUrl: url });
}

/** Fetches the raw HTML document and reports HTTP failures as loader errors. */
async function fetchHtmlDocument(url: string): Promise<string> {
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Failed to fetch HTML document from ${url}: ${response.status}`);
  }

  return response.text();
}

/**
 * Extracts and parses all JSON-LD script blocks from an HTML document.
 *
 * Multiple blocks are returned as an array because JSON-LD pages may publish
 * more than one structured-data object. The normalizer decides which object
 * represents the loaded specification.
 */
function extractJsonLd(html: string): unknown[] {
  const scriptPattern =
    /<script\b(?=[^>]*type\s*=\s*["']application\/ld\+json["'])[^>]*>([\s\S]*?)<\/script>/gi;
  const jsonLd: unknown[] = [];
  let match = scriptPattern.exec(html);

  while (match) {
    const content = match[1]?.trim();

    if (content) {
      jsonLd.push(JSON.parse(content));
    }

    match = scriptPattern.exec(html);
  }

  if (jsonLd.length === 0) {
    throw new Error("No JSON-LD script found in the specification page.");
  }

  return jsonLd;
}
